name: Deploy Helpdesk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Test Git Pull
        run: |
          git pull || { echo "git pull failed!"; exit 1; }
          echo "Git pull executed successfully."

      - name: Test PM2 Restart
        run: |
          pm2 restart all || { echo "PM2 restart failed!"; exit 1; }
          echo "PM2 processes restarted successfully."
